spring:
  application:
    name: wulianmei
  druid:
    url: jdbc:mysql://127.0.0.1:3306/wulianmei?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    maxActive: 30
    minIdle: 3
    maxWait: 10000
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    borrowConnectionTimeout: 30000
server:
  port: 8090

